# Site settings
title: Cal Poly Game Development
email: officers@cpgd.org
url: https://calpolygamedevelopmentclub.github.io/
description: "Cal Poly Game Development Club is focused on teaching all aspects of game creation along with providing a community that you can learn from and collaborate with. Simply put, we make games and connect our members with professionals in the game development industry."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: CPGD

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CPGameDev
  - title: facebook
    url: https://www.facebook.com/CPGameDev
  - title: linkedin
    url: https://www.linkedin.com/company/cpgd/about
  - title: github
    url: https://github.com/CalPolyGameDevelopmentClub

# Build settings
markdown: kramdown
permalink: pretty
